### ISSUE TITLE
org.astarte-platform.InterfaceName is not a valid interface name

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte_core#7]
Interface name validation should allow names such as `org.astarte-platform.InterfaceName`.

**Comment by rbino** [comment]
Expanding on this a little bit.
Right now we're allowing only alphanumeric characters and `.` in the interface name.
To be precise, we're matching the interface name against this regex:
```
~r/^[a-zA-Z]+(\.[a-zA-Z0-9]+)*$/
```

Since CQL only accepts [alpha-numeric characters and underscores](https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/cqlSyntax.html#Validcharactersinnames) in table names, and since sometimes the interface name has to be mapped onto a table name, we deal with it [here](https://github.com/astarte-platform/astarte_core/blob/ca33b91539c599ca6a4c44ed37ec16442bd7571a/lib/astarte_core/cql_utils.ex#L33) mainly by lowercasing everything and replacing `.` with `_` (plus a bunch of extra stuff that is not relevant here).

The point is, if we allow using also `-` in the interface name, we mainly have two choices when we have to map the interface name to a table: either we replace also `-` with `.` or we drop it alltogether.

The first will cause conflicts between, e.g., `com.my.pretty.Interface` and `com.my-pretty.Interface`, the second will cause will cause conflicts between, e.g., `com.my.PrettyInterface` and `com.my.Pretty-Interface`.

Whichever way we decide to go, this has to be documented.

**Comment by matt-mazzucato** [comment]
These are the examples we used to validate the regular expression for `interface_name`
```
OK:
JustInterfaceName1
JustInterfaceName
justinterfacename
com.astarte-platform.InterfaceName1
com.astarte-platform.InterfaceName
com.astarte-platform.interfacename
a.InterfaceName
com.a.InterfaceName
com.0.aa
aaa.a-.aaaaa
c0m.InterfaceName

Shouldn't be ok, but we are accepting it anyway:
com.a-.interfacename

Not ok:
com.-.InterfaceName
c-m.InterfaceName
a-.a
c-o-m.astarte-platform.interfacename
1JustInterfaceName
just-interface-name
com.astarte-platform.InterfaceName-
com.astarte-platform.InterfaceName.
-a.a
0.test.InterfaceName
0.InterfaceName
-
.
-.
```
